- name: Deploy recursor configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ powerdns_recursor_conf_base }}/{{ item }}"
  loop:
    - recursor.conf
    - recursor.lua

- name: Deploy auth configuration
  ansible.builtin.template:
    src: "{{ item }}.j2"
    dest: "{{ powerdns_auth_conf_base }}/{{ item }}"
  loop:
    - pdns.conf
