- name: Install extra packages
  ansible.builtin.package:
    name: "{{ powerdns_extra_os_packages }}"
    state: present

- name: Create PDNS account
  ansible.builtin.user:
    name: pdns
    uid: 953
    system: yes

- name: Create PowerDNS configuration and data folders
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: pdns
    mode: 0755
  loop: "{{ [powerdns_auth_conf_dirs, powerdns_auth_data_base, powerdns_recursor_conf_dirs] | flatten(1) }}"

- name: Pull in backend DB schema file
  ansible.builtin.get_url:
    url: "{{ powerdns_backend_schema_url }}"
    dest: "/tmp/backend.sql"

- name: Initialise DB
  ansible.builtin.shell: 
    cmd: "sqlite3 {{ powerdns_auth_data_base }}/pdns.sqlite3 < /tmp/backend.sql"
    creates: "{{ powerdns_auth_data_base }}/pdns.sqlite3"

- name: Change DB file pwermissions
  ansible.builtin.file:
    path: "{{ powerdns_auth_data_base }}/pdns.sqlite3"
    owner: pdns

